---
- name: Verify
  hosts: all
  become: true
  vars:
    vaultwarden_bind_ip: 127.0.0.1
    vaultwarden_bind_port: 8080
    vaultwarden_domain: http://{{ vaultwarden_bind_ip }}:{{ vaultwarden_bind_port }}/
    vaultwarden_user: vaultwarden
  tasks:
    - name: Run shared Vaultwarden verification tasks
      ansible.builtin.include_role:
        name: vaultwarden
        tasks_from: verify.yml

    - name: Wait for vaultwarden healthcheck endpoint
      ansible.builtin.uri:
        url: "{{ vaultwarden_domain }}/alive"
        method: GET
        status_code: 200
      register: health_check
      until: health_check.status == 200
      retries: 20
      delay: 5

    - name: Reboot the instance to test persistence
      ansible.builtin.reboot:
      become: true

    - name: Run shared Vaultwarden verification tasks after reboot
      ansible.builtin.include_role:
        name: vaultwarden
        tasks_from: verify.yml

    - name: Verify healthcheck after reboot
      ansible.builtin.uri:
        url: "{{ vaultwarden_domain }}/alive"
        method: GET
        status_code: 200
      register: health_check_post
      until: health_check_post.status == 200
      retries: 20
      delay: 5
