---
- name: Prepare secrets
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Write mock secrets file
      ansible.builtin.copy:
        dest: "{{ molecule_ephemeral_directory }}/secrets.yml"
        content: |
          secrets_public_eth_name: "eth1"
          secrets_private_eth_name: "eth2"
          secrets_default_eth_name: "eth3"
          secrets_public_interface_ip: "192.168.56.10"
          secrets_private_interface_ip: "192.168.56.11"
          secrets_private_interface_ipv6: "fd00:abcd::11"
          secrets_default_interface_ip: "192.168.56.12"
          secrets_default_interface_link_local_ipv6: "fe80::12"
          secrets_pihole_admin_password: "mock_pihole_pass"
          secrets_pihole_dhcp_start: "192.168.56.100"      # Excludes static server IPs
          secrets_pihole_dhcp_end: "192.168.56.200"
          secrets_pihole_local_ipv6: "fd00:abcd::11"
          secrets_lan_router_ip: "192.168.56.1"
          secrets_wireguard_port: 51820
          secrets_wireguard_server_url: "vpn.molecule.test"
          secrets_wireguard_allowed_ips: "192.168.56.0/24"
          secrets_vaultwarden_admin_password: "mock_vaultwarden_pass"
        mode: '0640'
