---
- name: Verify
  hosts: all
  become: true
  vars:
    caddy_user: services_user
  tasks:
    - name: Run shared Caddy verification tasks
      ansible.builtin.include_role:
        name: caddy
        tasks_from: verify.yml

    - name: Check Caddy reachability
      ansible.builtin.uri:
        url: "http://localhost:80"
        return_content: true
      register: caddy_response
      retries: 5
      delay: 5
      until: caddy_response.status == 200

    - name: Assert forwarding to http-echo
      ansible.builtin.assert:
        that:
          - "'hello from http-echo' in caddy_response.content"

    - name: Reboot the instance to test persistence
      ansible.builtin.reboot:
      become: true

    - name: Run shared Caddy verification tasks after reboot
      ansible.builtin.include_role:
        name: caddy
        tasks_from: verify.yml

    - name: Check Caddy reachability after reboot
      ansible.builtin.uri:
        url: "http://localhost:80"
        return_content: true
      register: caddy_response_post
      retries: 10
      delay: 5
      until: caddy_response_post.status == 200

    - name: Assert forwarding to http-echo after reboot
      ansible.builtin.assert:
        that:
          - "'hello from http-echo' in caddy_response_post.content"
